INSERT INTO currencies ("name", iso_code_2, iso_code_3, icon) VALUES
    ('Dollars','US','USD', '$'),
    ('Euro','EU','EUR', '€'),
    ('Rubles','RU','RUB', '₽');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('ADA','AD','ADA'),
    ('AED','AE','AED'),
    ('AFN','AF','AFN'),
    ('ALL','AL','ALL'),
    ('AMD','AM','AMD'),
    ('ANG','AN','ANG'),
    ('AOA','AO','AOA'),
    ('ARB','AR','ARB'),
    ('ARS','AR','ARS'),
    ('AUD','AU','AUD');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('AVAX','AV','AVA'),
    ('AWG','AW','AWG'),
    ('AZN','AZ','AZN'),
    ('BAM','BA','BAM'),
    ('BBD','BB','BBD'),
    ('BDT','BD','BDT'),
    ('BGN','BG','BGN'),
    ('BHD','BH','BHD'),
    ('BIF','BI','BIF'),
    ('BMD','BM','BMD');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('BNB','BN','BNB'),
    ('BND','BN','BND'),
    ('BOB','BO','BOB'),
    ('BRL','BR','BRL'),
    ('BSD','BS','BSD'),
    ('BTC','BT','BTC'),
    ('BTN','BT','BTN'),
    ('BWP','BW','BWP'),
    ('BYN','BY','BYN'),
    ('BYR','BY','BYR');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('BZD','BZ','BZD'),
    ('CAD','CA','CAD'),
    ('CDF','CD','CDF'),
    ('CHF','CH','CHF'),
    ('CLF','CL','CLF'),
    ('CLP','CL','CLP'),
    ('CNY','CN','CNY'),
    ('COP','CO','COP'),
    ('CRC','CR','CRC'),
    ('CUC','CU','CUC');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('CUP','CU','CUP'),
    ('CVE','CV','CVE'),
    ('CZK','CZ','CZK'),
    ('DAI','DA','DAI'),
    ('DJF','DJ','DJF'),
    ('DKK','DK','DKK'),
    ('DOP','DO','DOP'),
    ('DOT','DO','DOT'),
    ('DZD','DZ','DZD'),
    ('EGP','EG','EGP');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('ERN','ER','ERN'),
    ('ETB','ET','ETB'),
    ('ETH','ET','ETH'),
    ('FJD','FJ','FJD'),
    ('FKP','FK','FKP'),
    ('GBP','GB','GBP'),
    ('GEL','GE','GEL'),
    ('GGP','GG','GGP'),
    ('GHS','GH','GHS');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('GIP','GI','GIP'),
    ('GMD','GM','GMD'),
    ('GNF','GN','GNF'),
    ('GTQ','GT','GTQ'),
    ('GYD','GY','GYD'),
    ('HKD','HK','HKD'),
    ('HNL','HN','HNL'),
    ('HRK','HR','HRK'),
    ('HTG','HT','HTG'),
    ('HUF','HU','HUF');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('IDR','ID','IDR'),
    ('ILS','IL','ILS'),
    ('IMP','IM','IMP'),
    ('INR','IN','INR'),
    ('IQD','IQ','IQD'),
    ('IRR','IR','IRR'),
    ('ISK','IS','ISK'),
    ('JEP','JE','JEP'),
    ('JMD','JM','JMD'),
    ('JOD','JO','JOD');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('JPY','JP','JPY'),
    ('KES','KE','KES'),
    ('KGS','KG','KGS'),
    ('KHR','KH','KHR'),
    ('KMF','KM','KMF'),
    ('KPW','KP','KPW'),
    ('KRW','KR','KRW'),
    ('KWD','KW','KWD'),
    ('KYD','KY','KYD'),
    ('KZT','KZ','KZT');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('LAK','LA','LAK'),
    ('LBP','LB','LBP'),
    ('LKR','LK','LKR'),
    ('LRD','LR','LRD'),
    ('LSL','LS','LSL'),
    ('LTC','LT','LTC'),
    ('LTL','LT','LTL'),
    ('LVL','LV','LVL'),
    ('LYD','LY','LYD'),
    ('MAD','MA','MAD');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('MATIC','MA','MAT'),
    ('MDL','MD','MDL'),
    ('MGA','MG','MGA'),
    ('MKD','MK','MKD'),
    ('MMK','MM','MMK'),
    ('MNT','MN','MNT'),
    ('MOP','MO','MOP'),
    ('MRO','MR','MRO'),
    ('MRU','MR','MRU'),
    ('MUR','MU','MUR');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('MVR','MV','MVR'),
    ('MWK','MW','MWK'),
    ('MXN','MX','MXN'),
    ('MYR','MY','MYR'),
    ('MZN','MZ','MZN'),
    ('NAD','NA','NAD'),
    ('NGN','NG','NGN'),
    ('NIO','NI','NIO'),
    ('NOK','NO','NOK'),
    ('NPR','NP','NPR');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('NZD','NZ','NZD'),
    ('OMR','OM','OMR'),
    ('ADA','AD','ADA'),
    ('AED','AE','AED'),
    ('AFN','AF','AFN'),
    ('ALL','AL','ALL'),
    ('AMD','AM','AMD'),
    ('ANG','AN','ANG'),
    ('AOA','AO','AOA'),
    ('ARB','AR','ARB');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('ARS','AR','ARS'),
    ('AUD','AU','AUD'),
    ('AVAX','AV','AVA'),
    ('AWG','AW','AWG'),
    ('AZN','AZ','AZN'),
    ('BAM','BA','BAM'),
    ('BBD','BB','BBD'),
    ('BDT','BD','BDT'),
    ('BGN','BG','BGN'),
    ('BHD','BH','BHD');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('BIF','BI','BIF'),
    ('BMD','BM','BMD'),
    ('BNB','BN','BNB'),
    ('BND','BN','BND'),
    ('BOB','BO','BOB'),
    ('BRL','BR','BRL'),
    ('BSD','BS','BSD'),
    ('BTC','BT','BTC'),
    ('BTN','BT','BTN'),
    ('BWP','BW','BWP');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('BYN','BY','BYN'),
    ('BYR','BY','BYR'),
    ('BZD','BZ','BZD'),
    ('CAD','CA','CAD'),
    ('CDF','CD','CDF'),
    ('CHF','CH','CHF'),
    ('CLF','CL','CLF'),
    ('CLP','CL','CLP'),
    ('CNY','CN','CNY'),
    ('COP','CO','COP');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('CRC','CR','CRC'),
    ('CUC','CU','CUC'),
    ('CUP','CU','CUP'),
    ('CVE','CV','CVE'),
    ('CZK','CZ','CZK'),
    ('DAI','DA','DAI'),
    ('DJF','DJ','DJF'),
    ('DKK','DK','DKK'),
    ('DOP','DO','DOP'),
    ('DOT','DO','DOT');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('DZD','DZ','DZD'),
    ('EGP','EG','EGP'),
    ('ERN','ER','ERN'),
    ('ETB','ET','ETB'),
    ('ETH','ET','ETH'),
    ('EUR','EU','EUR'),
    ('FJD','FJ','FJD'),
    ('FKP','FK','FKP'),
    ('GBP','GB','GBP'),
    ('GEL','GE','GEL');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('GGP','GG','GGP'),
    ('GHS','GH','GHS'),
    ('GIP','GI','GIP'),
    ('GMD','GM','GMD'),
    ('GNF','GN','GNF'),
    ('GTQ','GT','GTQ'),
    ('GYD','GY','GYD'),
    ('HKD','HK','HKD'),
    ('HNL','HN','HNL'),
    ('HRK','HR','HRK');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('HTG','HT','HTG'),
    ('HUF','HU','HUF'),
    ('IDR','ID','IDR'),
    ('ILS','IL','ILS'),
    ('IMP','IM','IMP'),
    ('INR','IN','INR'),
    ('IQD','IQ','IQD'),
    ('IRR','IR','IRR'),
    ('ISK','IS','ISK'),
    ('JEP','JE','JEP');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('JMD','JM','JMD'),
    ('JOD','JO','JOD'),
    ('JPY','JP','JPY'),
    ('KES','KE','KES'),
    ('KGS','KG','KGS'),
    ('KHR','KH','KHR'),
    ('KMF','KM','KMF'),
    ('KPW','KP','KPW'),
    ('KRW','KR','KRW'),
    ('KWD','KW','KWD');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('KYD','KY','KYD'),
    ('KZT','KZ','KZT'),
    ('LAK','LA','LAK'),
    ('LBP','LB','LBP'),
    ('LKR','LK','LKR'),
    ('LRD','LR','LRD'),
    ('LSL','LS','LSL'),
    ('LTC','LT','LTC'),
    ('LTL','LT','LTL'),
    ('LVL','LV','LVL');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('LYD','LY','LYD'),
    ('MAD','MA','MAD'),
    ('MATIC','MA','MAT'),
    ('MDL','MD','MDL'),
    ('MGA','MG','MGA'),
    ('MKD','MK','MKD'),
    ('MMK','MM','MMK'),
    ('MNT','MN','MNT'),
    ('MOP','MO','MOP'),
    ('MRO','MR','MRO');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('MRU','MR','MRU'),
    ('MUR','MU','MUR'),
    ('MVR','MV','MVR'),
    ('MWK','MW','MWK'),
    ('MXN','MX','MXN'),
    ('MYR','MY','MYR'),
    ('MZN','MZ','MZN'),
    ('NAD','NA','NAD'),
    ('NGN','NG','NGN'),
    ('NIO','NI','NIO');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('NOK','NO','NOK'),
    ('NPR','NP','NPR'),
    ('NZD','NZ','NZD'),
    ('OMR','OM','OMR'),
    ('PAB','PA','PAB'),
    ('PEN','PE','PEN'),
    ('PGK','PG','PGK'),
    ('PHP','PH','PHP'),
    ('PKR','PK','PKR'),
    ('PLN','PL','PLN');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('PYG','PY','PYG'),
    ('QAR','QA','QAR'),
    ('RON','RO','RON'),
    ('RSD','RS','RSD'),
    ('RWF','RW','RWF'),
    ('SAR','SA','SAR'),
    ('SBD','SB','SBD'),
    ('SCR','SC','SCR'),
    ('SDG','SD','SDG');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('SEK','SE','SEK'),
    ('SGD','SG','SGD'),
    ('SHP','SH','SHP'),
    ('SLL','SL','SLL'),
    ('SOL','SO','SOL'),
    ('SOS','SO','SOS'),
    ('SRD','SR','SRD'),
    ('STD','ST','STD'),
    ('STN','ST','STN'),
    ('SVC','SV','SVC');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('SYP','SY','SYP'),
    ('SZL','SZ','SZL'),
    ('THB','TH','THB'),
    ('TJS','TJ','TJS'),
    ('TMT','TM','TMT'),
    ('TND','TN','TND'),
    ('TOP','TO','TOP'),
    ('TRY','TR','TRY'),
    ('TTD','TT','TTD'),
    ('TWD','TW','TWD');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('TZS','TZ','TZS'),
    ('UAH','UA','UAH'),
    ('UGX','UG','UGX'),
    ('USDC','US','USD'),
    ('USDT','US','USD'),
    ('UYU','UY','UYU'),
    ('UZS','UZ','UZS'),
    ('VEF','VE','VEF'),
    ('VES','VE','VES');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('VND','VN','VND'),
    ('VUV','VU','VUV'),
    ('WST','WS','WST'),
    ('XAF','XA','XAF'),
    ('XAG','XA','XAG'),
    ('XAU','XA','XAU'),
    ('XCD','XC','XCD'),
    ('XDR','XD','XDR'),
    ('XOF','XO','XOF'),
    ('XPD','XP','XPD');
INSERT INTO currencies ("name", iso_code_2, iso_code_3) VALUES
    ('XPF','XP','XPF'),
    ('XPT','XP','XPT'),
    ('XRP','XR','XRP'),
    ('YER','YE','YER'),
    ('ZAR','ZA','ZAR'),
    ('ZMK','ZM','ZMK'),
    ('ZMW','ZM','ZMW'),
    ('ZWL','ZW','ZWL');
