### GET request to get user by id
GET {{host}}}/{{user-url}}/{{userId}}
Authorization: {{authorization}}

### GET request to get all users
GET {{host}}}/{{user-url}}/all
Authorization: {{authorization}}

### PUT request to update user
PUT {{host}}}/{{user-url}}/update
Authorization: {{authorization}}
Content-Type: application/json

{
  "id": "1",
  "email": "lobanov.nikita2018@yandex.ru",
  "phone": "88005553535",
  "password": null,
  "confirmPassword": null
}
###
PUT http://localhost:8081/api/v1/users/update
Content-Type: application/json

{
  "id": "1",
  "email": "lobanov.nikita2018@yandex.ru",
  "phone": "88005553535",
  "password": null,
  "confirmPassword": null
}
### POST request to ban user by id
POST {{host}}}/{{user-url}}/ban/{{userId}}
Authorization: {{authorization}}

### DELETE request to delete user by id
DELETE {{host}}}/{{user-url}}/delete/{{userId}}
Authorization: {{authorization}}
