POST http://localhost:8081/api/v1/auth/register
Content-Type: application/json

{
  "name": "Nikita",
  "lastname": "Lobanov",
  "patronymic": "Michailovich",
  "series": 1234,
  "number": 567890,
  "birthday": "11.11.1111",
  "gender": "M",
  "departmentCode": "660-111",
  "issuedBy": "AAAAA",
  "issuedDate": "11.11.1120",
  "address": "BBBBBB",
  "email": "admin@yandex.ru",
  "password": "qwerty123!",
  "confirmPassword": "qwerty123!",
  "url": "http://localhost:3000?code="
}

###

GET http://localhost:8080/core/api/v1/users/all
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJsb2Jhbm92Lm5pa2l0YTIwMThAeWFuZGV4LnJ1IiwiYXV0aG9yaXR5IjoiVVNFUiIsImVuYWJsZWQiOmZhbHNlLCJpYXQiOjE3MTU0NDMyNzYsIm5iZiI6MTcxNTQ0MzI3NiwiZXhwIjoxNzE1NDQzNTc2fQ.uC1hRtIBJUQ_5lwe0GN5PneOSup0YmlVPdFRuOHOYnUfrG2Rdb06isbS-CVeqMWC

###

GET http://localhost:8081/api/v1/category/upload
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJsb2Jhbm92Lm5pa2l0YTIwMThAeWFuZGV4LnJ1IiwiYXV0aG9yaXR5IjoiVVNFUiIsImVuYWJsZWQiOmZhbHNlLCJpYXQiOjE3MTUyODUwMTMsIm5iZiI6MTcxNTI4NTAxMywiZXhwIjoxNzE1Mjg1MzEzfQ.uVzrKb_x3Yz8x3BG5avroPd_qiPzEFJjqpx84vtl3yvJA4ADPmfyOZgPEroxUfNg


###

GET http://localhost:8080/core/test

###

POST http://localhost:8081/api/v1/auth/login
Content-Type: application/json

{
  "email": "user@mail.ru",
  "password": "qwert"
}

###

GET http://localhost:8080/impl/api/v1/auth/access
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI1IiwiaWF0IjoxNzE0NTQ2OTA0LCJuYmYiOjE3MTQ1NDY5MDQsImV4cCI6MTcxNzEzODkwNH0.jawyehl_dMooU81smyKFBH6h_eO-NQ6oiMGbMgt49wrhc_tQhijwsTrSWMbdcK0P"
}

###

GET http://localhost:8081/api/v1/bank-info/upload

###

GET http://localhost:8081/api/v1/category/all

###

POST http://localhost:8081/api/v1/transactions/transfer/between-accounts
Content-Type: application/json

{
  "from": 1,
  "to": 3,
  "amount": 200000
}

###

POST http://localhost:8081/api/v1/cards/create
Content-Type: application/json

{
  "accountId": "2"
}

###

POST http://localhost:8081/api/v1/accounts/create
Content-Type: application/json

{
  "name": "Third",
  "currencyId": "2",
  "typeId": "1",
  "ownerId": "1"
}

###

POST http://localhost:8081/api/v1/transactions/transfer/phone
Content-Type: application/json

{
  "from": 1,
  "phone": "89826335964",
  "amount": 1000,
  "message": "aaa"
}

###

GET http://localhost:8081/api/v1/transactions/expenses/user/1