POST http://localhost:8083/impl/api/v1/auth/register
Content-Type: application/json

{
  "name": "Nikita",
  "lastname": "Lobanov",
  "patronymic": "Michailovich",
  "email": "lobanov.nikita2018@yandex.ru",
  "password": "qwerty123!",
  "confirmPassword": "qwerty123!"
}

###

GET http://localhost:8083/impl/api/v1/users/6
